version: "3.8"

services:
  gdrive:
    build: ./gdrive
    container_name: gdrive
    expose:
      - "3000"
    environment:
      - RD_TOKEN=
      - ENTRY_DOMAIN=
    restart: always
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - gdrive
    restart: always
